const navMenu = [
  { id: "menu1", title: "UP TO 51%OFF ✨" },
  { id: "menu2", title: "Y-3 30% OFF 🌟" },
  { id: "menu3", title: "LAST SIZE SALE 👕" },
  { id: "menu4", title: "COMFY SNEAKERS 👟" },
];

const sale = [
  { id: 0, url: "/saleman.avif", gender: "남성" },
  { id: 1, url: "/salewomen.avif", gender: "여성" },
  { id: 2, url: "/salekid.avif", gender: "키즈" },
  { id: 3, url: "/saleall.avif", gender: "전체" },
];
const best = [{ id: "menu1", title: "adidas Best 🔖" }];

const upTo = [
  {
    id: 0,
    url: "/upTo1.avif",
    title: "베이스볼 클래스 트레포일 캡",
    category: "Accessories",
    price: "35,000원",
  },
  {
    id: 1,
    url: "/upTo2.avif",
    title: "3S 베이비 티",
    category: "Clothing",
    price: "45,000원",
  },
  {
    id: 2,
    url: "/upTo3.avif",
    title: "가젤 볼드",
    category: "Shoes",
    price: "139,000원",
  },
  {
    id: 4,
    url: "/upTo4.avif",
    title: "VRCT 그래픽 티",
    category: "Clothing",
    price: "55,000원",
  },
  {
    id: 5,
    url: "/upTo5.avif",
    title: "사모아",
    category: "shoes",
    price: "99,000원",
  },
  {
    id: 6,
    url: "/upTo6.avif",
    title: "Samoa Shoes",
    category: "shoes",
    price: "99,000원",
  },
  {
    id: 7,
    url: "/upTo7.avif",
    title: "런던",
    category: "shoes",
    price: "139,000원",
  },
  {
    id: 8,
    url: "/upTo8.avif",
    title: "VS 페이스 2.0",
    category: "shoes",
    price: "69,000원",
  },
  {
    id: 9,
    url: "/upTo9.avif",
    title: "런던",
    category: "shoes",
    price: "139,000원",
  },
  {
    id: 10,
    url: "/upTo10.avif",
    title: "가젤 85",
    category: "shoes",
    price: "159,000원",
  },
  {
    id: 11,
    url: "/upTo11.avif",
    title: "파워리프트 5 웨이트리프팅",
    category: "shoes",
    price: "159,000원",
  },
  {
    id: 12,
    url: "/upTo12.avif",
    title: "컨트리 OG",
    category: "shoes",
    price: "139,000원",
  },
];
const y3 = [
  {
    id: 0,
    url: "/y1.avif",
    title: "Y-3 가젤",
    category: "Shoes",
    price: "449,000원",
    salePrice: "314,300원 회원 전용",
  },
  {
    id: 1,
    url: "/y2.avif",
    title: "Y-3 샌들",
    category: "Shoes",
    price: "409,000원",
    salePrice: "286,300원 회원 전용",
  },
  {
    id: 2,
    url: "/y3.avif",
    title: "Y-3 샌들",
    category: "Shoes",
    price: "409,000원",
    salePrice: "286,300원 회원 전용",
  },
  {
    id: 3,
    url: "/y4.avif",
    title: "Y-3 릴랙스드 반팔 티",
    category: "Clothing",
    price: "129,000원",
    salePrice: "90,300원 회원 전용",
  },
  {
    id: 4,
    url: "/y5.avif",
    title: "Y-3 프리미엄 반팔 티",
    category: "Clothing",
    price: "199,000원",
    salePrice: "139,300원 회원 전용",
  },
  {
    id: 5,
    url: "/y6.avif",
    title: "Y-3 탱크탑 드레스",
    category: "Clothing",
    price: "279,000원",
    salePrice: "195,300원 회원 전용",
  },
  {
    id: 6,
    url: "/y7.avif",
    title: "Y-3 나일론 트윌 쇼츠",
    category: "Clothing",
    price: "379,000원",
    salePrice: "265,300원 회원 전용",
  },
  {
    id: 7,
    url: "/y8.avif",
    title: "Y-3 프리미엄 긴팔티",
    category: "Clothin g",
    price: "229,000원",
    salePrice: "160,300원 회원 전용",
  },
  {
    id: 8,
    url: "/y9.avif",
    title: "Y-3 가이와",
    category: "shoes",
    price: "519,000원",
    salePrice: "363,300원 회원 전용",
  },
  {
    id: 9,
    url: "/y10.avif",
    title: "Y-3 가젤",
    category: "shoes",
    price: "499,000원",
    salePrice: "314,300원 회원 전용",
  },
  {
    id: 10,
    url: "/y11.avif",
    title: "Y-3 니짜 로우",
    category: "shoes",
    price: "409,000원",
    salePrice: "286,300원 회원 전용",
  },
  {
    id: 11,
    url: "/y12.avif",
    title: "Y-3 라이벌리",
    category: "shoes",
    price: "519,000원",
    salePrice: "363,300원 회원 전용",
  },
];
const last = [
  {
    id: 0,
    url: "/last1.avif",
    title: "Ultimashow Shoes",
    category: "Shoes",
    price: "69,000원",
    discount: "-30%",
    salePrice: "48,300원",
  },
  {
    id: 1,
    url: "/last2.avif",
    title: "런잇 티",
    category: "Clothing",
    price: "49,000원",
    discount: "-30%",
    salePrice: "34,300원",
  },
  {
    id: 2,
    url: "/last3.avif",
    title: "TERREX 멀티 우븐 팬츠",
    category: "Clothing",
    price: "99,000원",
  },
  {
    id: 3,
    url: "/last4.avif",
    title: "테니스 쿠션드 크루 삭스 1P",
    category: "Accesories",
    price: "25,000원",
  },
  {
    id: 4,
    url: "/last5.avif",
    title: "라이트웨이트 윈드레디 윈드브레이커",
    category: "Clothing",
    price: "129,000원",
  },
  {
    id: 5,
    url: "/last6.avif",
    title: "Z.N.E 원터라이즈드 풀집 후드 트랙",
    category: "Clothing",
    price: "139,000원",
  },
  {
    id: 6,
    url: "/last7.avif",
    title: "SST 트랙탑",
    category: "Clothing",
    price: "89,000원",
  },
  {
    id: 7,
    url: "/last8.avif",
    title: "에센셜 프렌치 테리 엠브로이더드 스몰 로고 스웨트셔츠",
    category: "Clothing",
    price: "79,000원",
  },
  {
    id: 8,
    url: "/lasg9.avif",
    title: "D4T하트레디 HIIT 티",
    category: "Clothing",
    price: "69,000원",
  },
  {
    id: 9,
    url: "/last10.avif",
    title: "스텔라 스포츠웨어 우븐 봄버 재킷",
    category: "Clothing",
    price: "419,000원",
  },
  {
    id: 10,
    url: "/last11.avif",
    title: "스텔라 TST 미디엄 서포트 브라",
    category: "Clothing",
    price: "119,000원",
  },
  {
    id: 11,
    url: "/last12.avif",
    title: "에어로레디 4 웨이 스트레치 쇼츠",
    category: "Clothing",
    price: "69,000원",
  },
];
const comfy = [
  {
    id: 0,
    url: "/comfy1.avif",
    title: "클라우트폼 무브 라운저",
    category: "Shoes",
    price: "69,000원",
  },
  {
    id: 1,
    url: "/comfy2.avif",
    title: "스피리테인 2000 스포츠",
    category: "Shoes",
    price: "109,000원",
  },
  {
    id: 2,
    url: "/comfy3.avif",
    title: "울트라부스트 1.0",
    category: "Shoes",
    price: "229,000원",
  },
  {
    id: 3,
    url: "/comfy4.avif",
    title: "dnfxmfkqntmxm1.0",
    category: "Shoes",
    price: "199,000원",
  },
  {
    id: 4,
    url: "/comfy5.avif",
    title: "X PLR 페이즈",
    category: "Shoes",
    price: "129,000원",
  },
  {
    id: 5,
    url: "/comfy6.avif",
    title: "X PLRPHASE",
    category: "Shoes",
    price: "129,000원",
  },
  {
    id: 6,
    url: "/comfy7.avif",
    title: "알파바운스",
    category: "Shose",
    price: "109,000원",
  },
  {
    id: 7,
    url: "/comfy8.avif",
    title: "알파엣지+",
    category: "Shoes",
    price: "89,000원",
  },
  {
    id: 8,
    url: "comfy9.avif",
    title: "클라우드폼 무브 라운저",
    category: "Shoes",
    price: "69,000원",
  },
  {
    id: 9,
    url: "/comfy10.avif",
    title: "스피리테인 2000",
    category: "Shoe",
    price: "109,000원",
  },
  {
    id: 10,
    url: "/comfy11.avif",
    title: "클라이마쿨 히트레디 클라이마",
    category: "Shoes",
    price: "109,000원",
  },
  {
    id: 11,
    url: "/comfy12.avif",
    title: "울트라부스트 1.0",
    category: "Shoes",
    price: "199,000원",
  },
];
const adidasBest = [
  {
    id: 1,
    url: "/best1.avif",
    title: "삼바 0G",
    category: "Originals",
    price: "139,000원",
    detail: [
      {
        id: "1-1",
        color: "Cloud White / Core Black / Clear Granite",
        url1: "/best1-1.avif",
        url2: "/best1-2.webm",
        url3: "/best1-3.avif",
        url4: "/best1-4.avif",
        size: [220, 230, 240, 250, 260, 270, 280, 290, 300],
      },
      {
        id: "1-2",
        color: "Core Black / Cloud White / Gum",
        url1: "/bestB2-1.avif",
        url2: "/bestB2-2.webm",
        url3: "/bestB2-3.avif",
        url4: "/bestB2-4.avif",
        size: [
          220, 225, 230, 235, 240, 245, 250, 255, 260, 265, 270, 275, 280, 285,
          290, 295,
        ],
      },
    ],
  },
  {
    id: 2,
    url: "/best2.avif",
    title: "삼바 0G",
    category: "Originals",
    price: "139,000원",
  },
  {
    id: 3,
    url: "/best3.avif",
    title: "YZY FOAM RNR ADULTS",
    category: "Originals",
    price: "139,000원",
  },
  {
    id: 4,
    url: "/best4.avif",
    title: "레알 마드리드 24/25 홈 저지",
    category: "Performance",
    price: "119,000원",
  },
  {
    id: 5,
    url: "/best5.avif",
    title: "아딜렛 24",
    category: "Originals",
    price: "79,000원",
  },
  {
    id: 6,
    url: "/best6.avif",
    title: "YZY FOAM RNR",
    category: "Originals",
    price: "129,000원",
  },
  {
    id: 7,
    url: "/best7.avif",
    title: "버뮤다",
    category: "Originals",
    price: "139,000원",
  },
  {
    id: 8,
    url: "/best8.avif",
    title: "런던",
    category: "Originals",
    price: "139,000원",
  },
  {
    id: 9,
    url: "/best9.avif",
    title: "아딜렛 클로그",
    category: "Sportswear",
    price: "55,000원",
  },
  {
    id: 10,
    url: "/best10.avif",
    title: "아디폼 SST 부츠",
    category: "Originals",
    price: "129,000원",
  },
  {
    id: 11,
    url: "/best11.avif",
    title: "삼바 Decon",
    category: "Originals",
    price: "179,000원",
  },
];
export { navMenu, sale, upTo, y3, last, comfy, adidasBest, best };
